project_name: co-author

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

gomod:
  proxy: true

builds:
  - id: linux-amd64
    binary: co-author
    main: .
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{ .Version }}

  - id: darwin-amd64
    binary: co-author
    main: .
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{ .Version }}

  - id: darwin-arm64
    binary: co-author
    main: .
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

  - id: windows-amd64
    binary: co-author
    main: .
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{ .Version }}
      - -buildmode=exe

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: erkanzileli
    name: co-author